version: '3.0'

# Used for local development

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    environment:
      AWS_ACCESS_KEY_ID: 'fakeMyKeyId'
      AWS_SECRET_ACCESS_KEY: 'fakeSecretAccessKey'
      REGION: 'us-east-1'
    volumes:
      - "./dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
